-- 1. Revenue by customer segment
SELECT
    customer_segment,
    COUNT(*) AS customer_count,
    SUM(purchase_amount) AS total_revenue,
    AVG(purchase_amount) AS avg_order_value
FROM dbo.customer_behavior_enriched
GROUP BY customer_segment
ORDER BY total_revenue DESC;

-- 2. High-value customers to retain
SELECT TOP 20
    customer_id,
    category,
    purchase_amount,
    subscription_status,
    frequency_of_purchases
FROM dbo.customer_watchlist
WHERE high_value_customer_flag = 1
ORDER BY purchase_amount DESC;

-- 3. Customers with churn risk
SELECT TOP 20
    customer_id,
    category,
    purchase_amount,
    customer_segment,
    frequency_of_purchases
FROM dbo.customer_watchlist
WHERE churn_risk_flag = 1
ORDER BY purchase_amount DESC;

-- 4. KPI summary for Power BI cards
SELECT
    kpi_name,
    kpi_value,
    unit,
    status,
    snapshot_date
FROM dbo.kpi_snapshot
ORDER BY kpi_name;

-- 5. Automation alerts generated by the rule engine
SELECT
    snapshot_date,
    alert_type,
    severity,
    message
FROM dbo.automation_alerts
ORDER BY snapshot_date DESC, severity DESC;
